name: Gateway Preview App
on:
  pull_request:
    types: [opened, reopened, synchronize, closed]

env:
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
  FLY_REGION: jnb
  FLY_ORG: personal

jobs:
  deploy-gateway-preview:
    name: Deploy to Neon and Fly.io
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    outputs:
      url: ${{ steps.deploy.outputs.url }}
    concurrency:
      group: pr-${{ github.event.number }}
    environment:
      name: gateway-preview
      url: ${{ steps.deploy.outputs.url }}

    steps:
      - name: Get code
        uses: actions/checkout@v6

      - name: Install pnpm
        uses: pnpm/action-setup@v6
        with:
          version: 10.33.2

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 24
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Get git branch name
        id: branch-name
        uses: tj-actions/branch-names@v9
      
      - name: Create database branch on Neon
        id: create-neon-branch
        uses: neondatabase/create-branch-action@v5
        with:
          project_id: ${{ secrets.NEON_PROJECT_ID }}
          username: "neondb_owner"
          parent: production
          branch_name: preview/${{ steps.branch-name.outputs.current_branch }}
          api_key: ${{ secrets.NEON_API_KEY }}

      - name: Set DATABASE_URL env var
        run: |
          echo "DATABASE_URL=${{ steps.create-neon-branch.outputs.db_url_with_pooler }}" >> "$GITHUB_ENV"

      - name: Deploy database migrations to preview branch on Neon
        run: pnpm --filter @postroll/database db:deploy
        env:
          DIRECT_URL: ${{ env.DATABASE_URL }}

      - name: Deploy Gateway PR App to Fly.io
        id: deploy
        uses: superfly/fly-pr-review-apps@1.6.0
        with:
          secrets: DATABASE_URL=${{ env.DATABASE_URL }}

      - name: Comment on Pull Request
        uses: mshick/add-pr-comment@v3
        with:
          message: |
            Fly Preview URL :balloon: : ${{ steps.deploy.outputs.url }}
            Neon branch :elephant: : https://console.neon.tech/app/projects/${{ secrets.NEON_PROJECT_ID }}/branches/${{ steps.create-neon-branch.outputs.branch_id }}
          delete-on-status: closed
